# Generated by Django 5.0 on 2023-12-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_master',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='department_master',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='designation_master',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='division_master',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee_category_master',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='qualification_master',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
