# Generated by Django 5.0 on 2024-01-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0002_class_master_status_department_master_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_category_master',
            name='area',
            field=models.IntegerField(choices=[(1, 'Teacher'), (2, 'Librarian'), (3, 'cafeteria'), (4, 'Accountant'), (5, 'Others')]),
        ),
    ]
