# Generated by Django 5.0 on 2024-01-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0003_alter_employee_category_master_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sstatus', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='subjectclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.class_master')),
                ('subid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.subjects')),
            ],
        ),
    ]
