# Generated by Django 5.0 on 2024-01-15 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_master', '0004_subjects_subjectclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('mob', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('j_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=100)),
                ('gender', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'others')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcode/')),
                ('status', models.IntegerField(default=1)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.department_master')),
                ('des_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.designation_master')),
                ('emp_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.employee_category_master')),
                ('qual_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.qualification_master')),
            ],
        ),
        migrations.CreateModel(
            name='emp_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='designation_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('des_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.designation_master')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='department_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.department_master')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='scd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.class_master')),
                ('div_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.division_master')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employee')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.subjects')),
            ],
        ),
    ]
