# Generated by Django 5.0 on 2024-01-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_employee', '0002_alter_department_employee_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_employee',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designation_employee',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_salary',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
